### ISSUE TITLE
Service is running, but no bot messages

### ISSUE THREAD

**Issue by ghost** [flakeparadigm/telegram1090#7]
Hi, I have the service running, but I get no messages on the bot. How can I test if the bot is running correctly?

**Comment by flakeparadigm** [comment]
After the service has been started, did you message the bot with the `subscribe` command? It's not really clear in the instructions, but the bot will only know what Telegram user(s) to send the messages to because they messaged `subscribe` to the bot.

The general idea is:
1. Service starts
2. Service loads the Telegram Chat IDs saved by the service previously (if a save file is found)
3. Bot receives a `subscribe` command and forwards it to the Service
4. Service saves the Chat ID that subscribed so it will know where to send future messages
5. If the bot receives an `unsubscribe` command, then it forwards it to the Service and the service removes the corresponding Chat ID from its saved list of Chat IDs

**Comment by ghost** [comment]
Thanks, just double checked it and I had a typo in my bot commands.

**Comment by flakeparadigm** [comment]
Good to hear it's working for you now! 🎉
